#!/usr/bin/env python3
"""Rewrite Galaxy requirements.yml for offline file/HTTP install.

Scans collections/*.tar.gz and writes a requirements.yml whose entries are
local tarball paths (relative to the galaxy artifact root). High-side clients:

  cd /srv/offline/galaxy
  ansible-galaxy collection install -r requirements.yml -p /usr/share/ansible/collections

Optional --base-url rewrites entries to absolute HTTP URLs for remote control nodes.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "galaxy_root",
        type=Path,
        help="artifacts/galaxy root (contains collections/)",
    )
    ap.add_argument(
        "--base-url",
        default="",
        help="If set, name entries become {base}/collections/<file>",
    )
    ap.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Output requirements.yml (default: <galaxy_root>/requirements.yml)",
    )
    args = ap.parse_args()
    root: Path = args.galaxy_root.resolve()
    coll = root / "collections"
    if not coll.is_dir():
        print(f"ERROR: collections dir missing: {coll}", file=sys.stderr)
        return 1

    tarballs = sorted(
        p.name
        for p in coll.iterdir()
        if p.is_file() and p.name.endswith(".tar.gz") and not p.name.startswith(".")
    )
    if not tarballs:
        print(f"WARN: no collection tarballs in {coll}", file=sys.stderr)

    base = args.base_url.rstrip("/")
    lines = [
        "---",
        "# Generated by otk-build for offline ansible-galaxy install.",
        "# Run from this directory, or use absolute/HTTP names below.",
        "collections:",
    ]
    for name in tarballs:
        if base:
            entry = f"{base}/collections/{name}"
        else:
            entry = f"collections/{name}"
        lines.append(f"  - name: {entry}")

    out = args.out or (root / "requirements.yml")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"OK: wrote {out} ({len(tarballs)} collection(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
