#!/bin/bash
#
# Derived from the air-gap image scripts published with Rancher releases
# (rancher/rancher, Apache License 2.0). Substantially modified: digest-tag
# pinning, image-label version resolution, a lock file, platform pinning and an
# upstream-drift check were added; the original argument handling and usage text
# are retained so the tools remain drop-in compatible.
#
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Pull images, retag with Hub digest + app version, save a multi-image tar.gz.
#
# Usage:
#   ./rancher-save-images.sh -l hack/airgap-images.txt -i redis-nifi.tar.gz
#   ./rancher-save-images.sh --check-upstream --lock rancher-images.lock

list="rancher-images.txt"
images="rancher-images.tar.gz"
source_registry=""
platform="${SAVE_PLATFORM:-linux/amd64}"
resolved_list="rancher-images.resolved.txt"
lock="rancher-images.lock"
check_upstream=""
keep_going=""
help=""

LIB="$(cd "$(dirname "$0")" && pwd)/rancher-image-lib.sh"
if [ ! -f "$LIB" ]; then
    echo "ERROR: missing ${LIB} (copy it next to this script)" >&2
    exit 1
fi
# shellcheck source=rancher-image-lib.sh
source "$LIB"
export RI_PLATFORM="${SAVE_PLATFORM:-linux/amd64}"

usage () {
    echo "USAGE: $0 [--image-list rancher-images.txt] [--images rancher-images.tar.gz]"
    echo "  [-s|--source-registry] source registry to pull images from in registry:port format."
    echo "  [-l|--image-list path] text file with list of images; one image per line."
    echo "  [-i|--images path] tar.gz generated by docker save."
    echo "  [-p|--platform os/arch] platform to pull (default linux/amd64; RKE2 nodes are amd64)."
    echo "  [--resolved-list path] tags actually saved (default rancher-images.resolved.txt)."
    echo "  [--lock path] upstream correlation file (default rancher-images.lock)."
    echo "  [--check-upstream] compare --lock to Hub; no pull/save. Exit 1 if digest moved."
    echo "  [--keep-going] skip failed pulls instead of exiting (upstream rancher behaviour)."
    echo "  [-h|--help] Usage message"
}

while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -i|--images)
        images="$2"; shift 2 ;;
        -l|--image-list)
        list="$2"; shift 2 ;;
        -s|--source-registry)
        source_registry="$2"; shift 2 ;;
        -p|--platform)
        platform="$2"; shift 2 ;;
        --resolved-list)
        resolved_list="$2"; shift 2 ;;
        --lock)
        lock="$2"; shift 2 ;;
        --check-upstream)
        check_upstream="true"; shift ;;
        --keep-going)
        keep_going="true"; shift ;;
        -h|--help)
        help="true"; shift ;;
        *)
        usage
        exit 1
        ;;
    esac
done

if [[ $help ]]; then
    usage
    exit 0
fi

export RI_PLATFORM="$platform"

if [[ $check_upstream ]]; then
    ri_check_upstream "$lock"
    exit $?
fi

if [ ! -f "$list" ]; then
    echo "ERROR: image list not found: ${list}" >&2
    exit 1
fi

source_registry="${source_registry%/}"
if [ -n "${source_registry}" ]; then
    source_registry="${source_registry}/"
fi

docker_uses_containerd_snapshotter () {
    docker info 2>/dev/null | grep -qi "containerd.snapshotter"
}

helm_available () {
    command -v helm >/dev/null 2>&1
}

helm_oci_ga () {
    local v major minor
    v=$(helm version --short 2>/dev/null | sed -n 's/^v\([0-9.]*\).*/\1/p')
    [ -z "$v" ] && return 1
    major=${v%%.*}
    minor=${v#*.}; minor=${minor%%.*}
    [ "$major" -gt 3 ] || { [ "$major" -eq 3 ] && [ "$minor" -ge 8 ]; }
}

is_oci_helm_chart () {
    [[ "$1" == *"rancher/charts/"* ]]
}

has_oci_charts=false
while IFS= read -r i || [ -n "$i" ]; do
    i="${i%%#*}"
    i="$(echo "$i" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
    [ -z "${i}" ] && continue
    if is_oci_helm_chart "${i}"; then
        has_oci_charts=true
        break
    fi
done < "${list}"

use_helm_for_charts=false
if $has_oci_charts; then
    if ! docker_uses_containerd_snapshotter; then
        if helm_available; then
            if ! helm_oci_ga; then
                echo "ERROR: helm CLI is older than v3.8.0; OCI chart support requires helm 3.8.0+." >&2
                exit 1
            fi
            echo "WARNING: Docker is not using the containerd snapshotter; falling back to helm CLI for OCI Helm charts."
            use_helm_for_charts=true
        else
            echo "ERROR: List contains OCI Helm charts; enable the containerd image store or install helm 3.8+." >&2
            exit 1
        fi
    fi
fi

if $use_helm_for_charts; then
    mkdir -p ./rancher-oci-charts
fi

tmp_resolved="$(mktemp)"
tmp_lock="$(mktemp)"
trap 'rm -f "$tmp_resolved" "$tmp_lock"' EXIT
ri_write_lock_header "$tmp_lock"

pulled=""
fail=0

while IFS= read -r raw || [ -n "$raw" ]; do
    i="${raw%%#*}"
    i="$(echo "$i" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
    [ -z "${i}" ] && continue

    if $use_helm_for_charts && is_oci_helm_chart "${i}"; then
        i="${source_registry}${i}"
        chart_version="${i#*:}"
        echo "Pulling chart: ${i}..."
        helm_error=$(helm pull "oci://${i%:*}" --version "${chart_version//_/+}" -d ./rancher-oci-charts 2>&1)
        if [ $? -eq 0 ]; then
            echo "Chart pull success: ${i}"
        else
            echo "Chart pull FAILED: ${i}"
            echo "${helm_error}"
            echo "ERROR: OCI Helm charts are required for Prime functionality."
            exit 1
        fi
        continue
    fi

    if ri_is_attestation_ref "$i"; then
        echo "SKIP attestation/provenance ref (not an app image): ${i}"
        continue
    fi

    listed="${source_registry}${i}"
    listed="$(ri_strip_docker_io "$listed")"
    pull_ref="$(ri_pull_ref "$listed")"
    img_path="$(ri_image_path "$listed")"
    orig_tag="$(ri_image_tag "$listed")"
    track="$(ri_track_ref "$listed")"

    if ri_is_sha_named_tag "$orig_tag"; then
        echo "Hub tag ${orig_tag} is provenance, not the image; pulling ${pull_ref} instead"
    fi

    echo "Pulling ${pull_ref}  platform=${platform}"
    pull_out="$(ri_docker_pull "$pull_ref" "$platform" 2>&1)"
    pull_rc=$?
    echo "$pull_out"
    if [ $pull_rc -ne 0 ]; then
        echo "Image pull failed: ${pull_ref}"
        if [[ $keep_going ]]; then
            fail=1
            continue
        fi
        exit 1
    fi

    source_digest="$(printf '%s\n' "$pull_out" | ri_parse_pull_digest)"
    if [ -z "$source_digest" ]; then
        source_digest="$(docker inspect --format '{{index .RepoDigests 0}}' "$pull_ref" 2>/dev/null | sed 's/.*@//')"
    fi
    if [ -z "$source_digest" ]; then
        echo "ERROR: could not read Hub digest for ${pull_ref}" >&2
        if [[ $keep_going ]]; then
            fail=1
            continue
        fi
        exit 1
    fi

    local_ref="$pull_ref"
    if ! docker inspect "$local_ref" >/dev/null 2>&1; then
        local_ref="${img_path}:${orig_tag}"
    fi
    if ! docker inspect "$local_ref" >/dev/null 2>&1; then
        local_ref="$(docker inspect --format '{{index .RepoTags 0}}' "$pull_ref" 2>/dev/null || true)"
    fi

    app_ver="$(ri_inspect_app_version "$local_ref")"
    if [ -z "$app_ver" ]; then
        echo "ERROR: ${pull_ref} has no org.opencontainers.image.version / APP_VERSION — not treating it as an app image (Hub sha256-* tags are Cosign/provenance)." >&2
        if [[ $keep_going ]]; then
            fail=1
            continue
        fi
        exit 1
    fi

    digest_tag="$(ri_digest_tag_name "$source_digest")"
    version_name="${img_path}:${app_ver}"
    digest_name="${img_path}:${digest_tag}"

    docker tag "$local_ref" "$version_name"
    docker tag "$local_ref" "$digest_name"
    echo "Tagged ${img_path}:${app_ver}  and  ${img_path}:${digest_tag}  (Hub ${source_digest})"

    save_tags=("$version_name" "$digest_name")
    if [ "$orig_tag" != "latest" ] && [ -n "$orig_tag" ] && ! ri_is_sha_named_tag "$orig_tag" && [ "$orig_tag" != "$app_ver" ] && [ -z "$(ri_image_digest "$listed")" ]; then
        orig_name="${img_path}:${orig_tag}"
        docker tag "$local_ref" "$orig_name"
        save_tags+=("$orig_name")
    fi
    # Keep `latest` only when that is what the list asked for — it is a moving tag.
    if [ "$orig_tag" = "latest" ]; then
        latest_name="${img_path}:latest"
        docker tag "$local_ref" "$latest_name"
        save_tags+=("$latest_name")
    fi

    for t in "${save_tags[@]}"; do
        echo "$t" >> "$tmp_resolved"
        pulled="${pulled} ${t}"
    done

    ri_write_lock_record "$tmp_lock" \
        "$listed" "$pull_ref" "$track" "$source_digest" "$digest_tag" \
        "$app_ver" "$version_name" "$(IFS=,; echo "${save_tags[*]}")" "$platform"

done < "${list}"

if [ ! -s "$tmp_resolved" ]; then
    echo "No docker images pulled; skipping ${images}."
    if [ "$fail" -ne 0 ]; then
        exit 1
    fi
    exit 0
fi

sort -u "$tmp_resolved" > "$resolved_list"
echo "Resolved tags written to ${resolved_list}:"
cat "$resolved_list"

cp "$tmp_lock" "$lock"
echo "Wrote ${lock}"

if ! ri_save_supports_platform; then
    echo "ERROR: docker save --platform is required (Docker 25+) so a multi-arch index is not packed. This host would otherwise miss linux/amd64 or include a broken index." >&2
    exit 1
fi

uniq_images="$(tr ' ' '\n' <<<"${pulled}" | sed '/^$/d' | sort -u | tr '\n' ' ')"
count="$(echo "$uniq_images" | wc -w | tr -d '[:space:]')"
echo "Creating ${images} with ${count} tags, platform ${platform}"
set -o pipefail
# shellcheck disable=SC2086
docker save --platform "$platform" ${uniq_images} | gzip --stdout > "${images}"
save_rc=$?
set +o pipefail
if [ "$save_rc" -ne 0 ]; then
    echo "ERROR: docker save --platform ${platform} failed" >&2
    rm -f "${images}"
    exit 1
fi
echo "Saved ${images} ($(wc -c < "${images}" | tr -d ' ') bytes)"
echo "Pin on the basic registry with the sha256-<digest> tag (Hub index digest). Semver is an alias from the image label and can stay put across rebuilds."
echo "Later: $0 --check-upstream --lock ${lock}"
