#!/bin/bash
#
# Derived from the air-gap image scripts published with Rancher releases
# (rancher/rancher, Apache License 2.0). Substantially modified: digest-tag
# pinning, image-label version resolution, a lock file, platform pinning and an
# upstream-drift check were added; the original argument handling and usage text
# are retained so the tools remain drop-in compatible.
#
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Load a tar from rancher-save-images.sh and push tags to a basic registry.
# Pushes the Hub digest *tag name* (sha256-<hex>) and the app-version alias.
# Does not attempt to preserve Hub content digests — a basic registry rewrites them.

images="rancher-images.tar.gz"
list="rancher-images.txt"
resolved_list="rancher-images.resolved.txt"
windows_image_list=""
windows_versions="1809"
source_registry=""
help=""

LIB="$(cd "$(dirname "$0")" && pwd)/rancher-image-lib.sh"
if [ ! -f "$LIB" ]; then
    echo "ERROR: missing ${LIB} (copy it next to this script)" >&2
    exit 1
fi
# shellcheck source=rancher-image-lib.sh
source "$LIB"

usage () {
    echo "USAGE: $0 [--images rancher-images.tar.gz] [--source-registry index.docker.io] --registry my.registry.com:5000"
    echo "  [-l|--image-list path] original list (used if no resolved list)."
    echo "  [--resolved-list path] tags saved by rancher-save-images.sh (default rancher-images.resolved.txt)."
    echo "  [-i|--images path] tar.gz generated by docker save."
    echo "  [-r|--registry registry:port] target private registry in the registry:port format."
    echo "  [-s|--source-registry registry:port] prefix of names inside the tar (usually empty)."
    echo "  [--windows-image-list path] text file with list of images used in Windows. Windows image mirroring is skipped when this is empty."
    echo "  [--windows-versions version] Comma separated Windows versions. e.g., \"1809,ltsc2022\". (Default \"1809\")"
    echo "  [-h|--help] Usage message"
}

push_manifest () {
    export DOCKER_CLI_EXPERIMENTAL=enabled
    manifest_list=()
    for i in "${arch_list[@]}"
    do
        manifest_list+=("$1-${i}")
    done

    echo "Preparing manifest $1, list[${arch_list[@]}]"
    docker manifest create "$1" "${manifest_list[@]}" --amend
    docker manifest push "$1" --purge
}

while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -r|--registry)
        target_registry="$2"; shift 2 ;;
        -s|--source-registry)
        source_registry="$2"; shift 2 ;;
        -l|--image-list)
        list="$2"; shift 2 ;;
        --resolved-list)
        resolved_list="$2"; shift 2 ;;
        -i|--images)
        images="$2"; shift 2 ;;
        --windows-image-list)
        windows_image_list="$2"; shift 2 ;;
        --windows-versions)
        windows_versions="$2"; shift 2 ;;
        -h|--help)
        help="true"; shift ;;
        *)
        usage
        exit 1
        ;;
    esac
done
if [[ -z "${target_registry}" ]]; then
    usage
    exit 1
fi
if [[ $help ]]; then
    usage
    exit 0
fi

target_registry="${target_registry%/}/"
source_registry="${source_registry%/}"
if [ -n "${source_registry}" ]; then
    source_registry="${source_registry}/"
fi

docker_uses_containerd_snapshotter () {
    docker info 2>/dev/null | grep -qi "containerd.snapshotter"
}

helm_available () {
    command -v helm >/dev/null 2>&1
}

helm_oci_ga () {
    local v major minor
    v=$(helm version --short 2>/dev/null | sed -n 's/^v\([0-9.]*\).*/\1/p')
    [ -z "$v" ] && return 1
    major=${v%%.*}
    minor=${v#*.}; minor=${minor%%.*}
    [ "$major" -gt 3 ] || { [ "$major" -eq 3 ] && [ "$minor" -ge 8 ]; }
}

is_oci_helm_chart () {
    [[ "$1" == *"rancher/charts/"* ]]
}

push_list="$list"
if [ -f "$resolved_list" ]; then
    echo "Using resolved tag list ${resolved_list} (Hub digest tags + app-version aliases)"
    push_list="$resolved_list"
fi
if [ ! -f "$push_list" ]; then
    echo "ERROR: image list not found: ${push_list}" >&2
    exit 1
fi

has_oci_charts=false
while IFS= read -r i || [ -n "$i" ]; do
    i="${i%%#*}"
    i="$(echo "$i" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
    [ -z "${i}" ] && continue
    if is_oci_helm_chart "${i}"; then
        has_oci_charts=true
        break
    fi
done < "${list}"

use_helm_for_charts=false
if $has_oci_charts; then
    if ! docker_uses_containerd_snapshotter; then
        if helm_available; then
            if ! helm_oci_ga; then
                echo "ERROR: helm CLI is older than v3.8.0; OCI chart support requires helm 3.8.0+." >&2
                exit 1
            fi
            echo "WARNING: Docker is not using the containerd snapshotter; falling back to helm CLI for OCI Helm charts."
            use_helm_for_charts=true
        else
            echo "ERROR: List contains OCI Helm charts; enable the containerd image store or install helm 3.8+." >&2
            exit 1
        fi
    fi
fi

docker load --input "${images}"

linux_images=()
while IFS= read -r i || [ -n "$i" ]; do
    i="${i%%#*}"
    i="$(echo "$i" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
    [ -z "${i}" ] && continue
    linux_images+=("${i}")
done < "${push_list}"

arch_list=()
if [[ -n "${windows_image_list}" ]]; then
    IFS=',' read -r -a versions <<< "$windows_versions"
    for version in "${versions[@]}"
    do
        arch_list+=("windows-${version}")
    done

    windows_images=()
    while IFS= read -r i || [ -n "$i" ]; do
        [ -z "${i}" ] && continue
        windows_images+=("${i}")
    done < "${windows_image_list}"

    for i in "${windows_images[@]}"; do
        if [[ ! " ${linux_images[*]}" =~ " ${i}" ]]; then
            case $i in
            */*)
                image_name="${target_registry}${i}"
                ;;
            *)
                image_name="${target_registry}rancher/${i}"
                ;;
            esac
            push_manifest "${image_name}"
        fi
    done
fi

arch_list+=("linux-amd64")
for i in "${linux_images[@]}"; do
    [ -z "${i}" ] && continue
    if $use_helm_for_charts && is_oci_helm_chart "${i}"; then
        continue
    fi
    if ri_is_attestation_ref "$i"; then
        echo "SKIP attestation/provenance ref: ${i}"
        continue
    fi
    arch_suffix=""
    use_manifest=false
    if [[ (-n "${windows_image_list}") && " ${windows_images[*]}" =~ " ${i}" ]]; then
        use_manifest=true
        arch_suffix="-linux-amd64"
    fi

    src="${source_registry}$(ri_strip_docker_io "$i")"
    path_tag="$(ri_image_path "$src"):$(ri_image_tag "$src")"
    case $path_tag in
    */*)
        image_name="${target_registry}${path_tag}"
        ;;
    *)
        image_name="${target_registry}rancher/${path_tag}"
        ;;
    esac

    if ! docker inspect "$src" >/dev/null 2>&1; then
        src="$path_tag"
    fi
    echo "Push ${src} -> ${image_name}${arch_suffix}"
    docker tag "${src}" "${image_name}${arch_suffix}"
    docker push "${image_name}${arch_suffix}"

    if $use_manifest; then
        push_manifest "${image_name}"
    fi
done

if $use_helm_for_charts; then
    target_oci_base="${target_registry%/}"
    helm_push_args=()
    target_host="${target_oci_base#http://}"
    target_host="${target_host#https://}"
    if [[ "${target_host}" == localhost* || "${target_host}" == 127.0.0.1* || "${target_host}" == 0.0.0.0* ]]; then
        helm_push_args+=("--plain-http")
    fi
    while IFS= read -r i || [ -n "$i" ]; do
        i="${i%%#*}"
        i="$(echo "$i" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
        [ -z "${i}" ] && continue
        is_oci_helm_chart "${i}" || continue
        chart_repo="${i%:*}"
        chart_ver_oci="${i#*:}"
        chart_name="${chart_repo##*/}"
        chart_ns="${chart_repo%/*}"
        chart_file="./rancher-oci-charts/${chart_name}-${chart_ver_oci//_/+}.tgz"
        if [ ! -f "${chart_file}" ]; then
            echo "ERROR: Chart file missing: ${chart_file}"
            exit 1
        fi
        echo "Helm chart push: ${chart_file} -> oci://${target_oci_base}/${chart_ns}"
        helm push "${chart_file}" "oci://${target_oci_base}/${chart_ns}" "${helm_push_args[@]}"
    done < "${list}"
fi
